version: '3.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_credit_db
    ports:
      - 3307:3306
    volumes:
      - /Code:/Code
#      - my.cnf:/etc/mysql/my.cnf