insert into Punishments (name, serverity, trigger_score) values ('Enoxaparin Sodium', 8.134, -95.83);
insert into Punishments (name, serverity, trigger_score) values ('Menthol', 49.838, -30.85);
insert into Punishments (name, serverity, trigger_score) values ('Caffeine', 78.921, -69.12);
insert into Punishments (name, serverity, trigger_score) values ('English Walnut', 45.932, -2.82);
insert into Punishments (name, serverity, trigger_score) values ('Amoxicillin', 99.212, -51.54);
insert into Punishments (name, serverity, trigger_score) values ('TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE', 47.808, -60.11);
insert into Punishments (name, serverity, trigger_score) values ('Aspirin', 9.68, -34.7);
insert into Punishments (name, serverity, trigger_score) values ('Docusate Sodium', 75.75, -49.15);
insert into Punishments (name, serverity, trigger_score) values ('Ibuprofen', 76.443, -71.32);
insert into Punishments (name, serverity, trigger_score) values ('OCTINOXATE and ZINC OXIDE', 91.816, -85.68);
insert into Punishments (name, serverity, trigger_score) values ('Octinoxate and Titanium dioxide', 31.003, -96.4);
insert into Punishments (name, serverity, trigger_score) values ('ALCOHOL', 55.111, -30.41);
insert into Punishments (name, serverity, trigger_score) values ('TOPICAL STARCH', 81.546, -70.54);
insert into Punishments (name, serverity, trigger_score) values ('imiquimod', 69.24, -23.86);
insert into Punishments (name, serverity, trigger_score) values ('Methyldopa', 72.809, -50.39);
insert into Punishments (name, serverity, trigger_score) values ('Sulfamethoxazole and Trimethoprim', 84.764, -87.88);
insert into Punishments (name, serverity, trigger_score) values ('Hydralazine Hydrochloride', 73.894, -56.6);
insert into Punishments (name, serverity, trigger_score) values ('Diphenhydramine Hydrochloride', 64.843, -40.23);
insert into Punishments (name, serverity, trigger_score) values ('Dronabinol', 29.7, -62.32);
insert into Punishments (name, serverity, trigger_score) values ('oxymorphone hydrochoride', 7.138, -25.39);
insert into Punishments (name, serverity, trigger_score) values ('tramadol hydrochloride', 93.173, -79.61);
insert into Punishments (name, serverity, trigger_score) values ('Titanium Dioxide', 34.38, -11.54);
insert into Punishments (name, serverity, trigger_score) values ('Amoxicillin and Clavulanate Potassium', 8.329, -35.77);
insert into Punishments (name, serverity, trigger_score) values ('Plantain, English Plantago lanceolata', 39.153, -48.81);
insert into Punishments (name, serverity, trigger_score) values ('Nitrofurantoin Macrocrystals', 23.351, -8.15);
insert into Punishments (name, serverity, trigger_score) values ('DEXTROMETHORPHAN HYDROBROMIDE', 82.023, -69.8);
insert into Punishments (name, serverity, trigger_score) values ('testosterone', 6.717, -3.06);
insert into Punishments (name, serverity, trigger_score) values ('sarcobatus vermiculatus pollen', 96.503, -37.68);
insert into Punishments (name, serverity, trigger_score) values ('Acetaminophen', 85.082, -12.1);
insert into Punishments (name, serverity, trigger_score) values ('Prednisone', 45.321, -43.48);
insert into Punishments (name, serverity, trigger_score) values ('Lamotrigine', 54.679, -23.23);
insert into Punishments (name, serverity, trigger_score) values ('ETHYL ALCOHOL', 7.884, -78.54);
insert into Punishments (name, serverity, trigger_score) values ('Dimethicone, Octinoxate, Oxybenzone, Avobenzone, and Octocrylene', 28.13, -65.61);
insert into Punishments (name, serverity, trigger_score) values ('LIDOCAINE HYDROCHLORIDE, MENTHOL', 18.729, -76.49);
insert into Punishments (name, serverity, trigger_score) values ('OCTINOXATE and TITANIUM DIOXIDE', 85.806, -40.6);
insert into Punishments (name, serverity, trigger_score) values ('Dimethicone, Octinoxate, and Oxybenzone', 13.562, -77.99);
insert into Punishments (name, serverity, trigger_score) values ('Number Two Pine Mixture', 43.356, -58.69);
insert into Punishments (name, serverity, trigger_score) values ('tizanidine hydrochloride', 99.968, -7.47);
insert into Punishments (name, serverity, trigger_score) values ('Ibuprofen', 79.796, -1.95);
insert into Punishments (name, serverity, trigger_score) values ('ciprofloxacin hydrochloride', 44.527, -50.39);
insert into Punishments (name, serverity, trigger_score) values ('benztropine mesylate', 98.409, -95.94);
insert into Punishments (name, serverity, trigger_score) values ('TITANIUM DIOXIDE, ZINC OXIDE', 95.502, -79.65);
insert into Punishments (name, serverity, trigger_score) values ('SODIUM CHLORIDE', 81.424, -36.13);
insert into Punishments (name, serverity, trigger_score) values ('torsemide', 82.168, -95.87);
insert into Punishments (name, serverity, trigger_score) values ('Ropinirole Hydrochloride', 61.748, -56.72);
insert into Punishments (name, serverity, trigger_score) values ('HELIANTHEMUM CANADENSE', 77.484, -16.15);
insert into Punishments (name, serverity, trigger_score) values ('methylprednisolone acetate', 51.628, -2.19);
insert into Punishments (name, serverity, trigger_score) values ('Labetalol hydrochloride', 14.808, -25.6);
insert into Punishments (name, serverity, trigger_score) values ('Pyrithione zinc', 12.632, -42.51);
insert into Punishments (name, serverity, trigger_score) values ('ropivacaine hydrochloride', 67.872, -15.79);
insert into Punishments (name, serverity, trigger_score) values ('mupirocin calcium', 87.168, -15.04);
insert into Punishments (name, serverity, trigger_score) values ('TIZANIDINE', 42.865, -34.14);
insert into Punishments (name, serverity, trigger_score) values ('Heparin Sodium', 70.045, -55.39);
insert into Punishments (name, serverity, trigger_score) values ('Naratriptan', 86.947, -23.52);
insert into Punishments (name, serverity, trigger_score) values ('IBUPROFEN', 43.164, -97.52);
insert into Punishments (name, serverity, trigger_score) values ('Angelica sinensis radix, Aralia quinquefolia, Arg. nit., Arsenicum alb., Berber. aqui., Capsicum , Cinchona, Digitalis, Gelsemium, Hypericum, Ignatia, Iodium, Kali brom., Kali carb., Mag. phos., Nat. carb., Nat. mur., Phosphorus, Salix nigra, Sanguinaria, Sepia, Stramonium, Echinacea, Ginkgo', 92.746, -38.65);
insert into Punishments (name, serverity, trigger_score) values ('ACETAMINOPHEN and CODEINE', 61.563, -28.84);
insert into Punishments (name, serverity, trigger_score) values ('Nortriptyline Hydrochloride', 82.922, -95.1);
insert into Punishments (name, serverity, trigger_score) values ('Thuja occidentalis', 99.627, -86.65);
insert into Punishments (name, serverity, trigger_score) values ('Ethyl Alcohol', 52.845, -36.62);
insert into Punishments (name, serverity, trigger_score) values ('IRBESARTAN AND HYDROCHLOROTHIAZIDE', 87.457, -80.9);
insert into Punishments (name, serverity, trigger_score) values ('Grama Grass', 32.631, -7.17);
insert into Punishments (name, serverity, trigger_score) values ('Nicotine Polacrilex', 82.146, -15.67);
insert into Punishments (name, serverity, trigger_score) values ('Nicotine', 81.823, -52.74);
insert into Punishments (name, serverity, trigger_score) values ('Propranolol Hydrochloride', 16.803, -38.44);
insert into Punishments (name, serverity, trigger_score) values ('ARIPIPRAZOLE', 49.174, -74.11);
insert into Punishments (name, serverity, trigger_score) values ('Hydralazine Hydrochloride', 7.616, -14.3);
insert into Punishments (name, serverity, trigger_score) values ('Acetaminophen, Dextromethorphan Hydrobromide, Phenylephrine Hydrochloride', 55.464, -7.23);
insert into Punishments (name, serverity, trigger_score) values ('Ioversol', 16.849, -44.64);
insert into Punishments (name, serverity, trigger_score) values ('Arsenicum album, Calcarea carbonica, Ignatia amara, Kali carbonicum, Lachesis mutus, Natrum muriaticum, Phosphorus, Pulsatilla, Staphysagria', 67.404, -58.43);
insert into Punishments (name, serverity, trigger_score) values ('ACETAMINOPHEN', 61.513, -83.33);
insert into Punishments (name, serverity, trigger_score) values ('Aconitum napellus, Bromium, Coccus cacti, Corallium rubrum, Cuprum metallicum, Drosera, Hepar sulphuris calcareum, Iodium, Mephitis mephitica and Spongia tosta', 9.548, -11.61);
insert into Punishments (name, serverity, trigger_score) values ('Butalbital, Acetaminophen, and Caffeine', 71.783, -1.41);
insert into Punishments (name, serverity, trigger_score) values ('Nitrofurantoin Monohydrate/Macrocrystalline', 24.935, -53.28);
insert into Punishments (name, serverity, trigger_score) values ('Dextromethorphan HBr, Guaifenesin', 57.426, -73.72);
insert into Punishments (name, serverity, trigger_score) values ('Acetaminophen', 26.47, -98.49);
insert into Punishments (name, serverity, trigger_score) values ('DOCUSATE SODIUM', 29.58, -38.91);
insert into Punishments (name, serverity, trigger_score) values ('Menthol', 47.398, -78.09);
insert into Punishments (name, serverity, trigger_score) values ('Benzalkonium Chloride', 79.732, -24.62);
insert into Punishments (name, serverity, trigger_score) values ('Acetaminophen', 37.805, -31.95);
insert into Punishments (name, serverity, trigger_score) values ('Corn Pollen', 28.999, -11.98);
insert into Punishments (name, serverity, trigger_score) values ('Caffeine', 60.513, -68.08);
insert into Punishments (name, serverity, trigger_score) values ('hydroxyzine hydrochloride', 21.274, -77.58);
insert into Punishments (name, serverity, trigger_score) values ('Dipyridamole', 45.029, -11.62);
insert into Punishments (name, serverity, trigger_score) values ('BENZALKONIUM CHLORIDE', 51.815, -58.97);
insert into Punishments (name, serverity, trigger_score) values ('olmesartan medoxomil and hydrochlorothiazide', 86.698, -39.76);
insert into Punishments (name, serverity, trigger_score) values ('Arsenicum 30c, Chamomilla 30c, Cina 30c, Glononium 30c, Hyoscyamus 30c, Medorrhinum 30c, Stramonium 30c, Tarentula 30c, Veratrum Album 30c', 86.238, -18.74);
insert into Punishments (name, serverity, trigger_score) values ('Oxygen', 19.767, -46.05);
insert into Punishments (name, serverity, trigger_score) values ('Ropinirole Hydrochloride', 21.172, -91.26);
insert into Punishments (name, serverity, trigger_score) values ('FENTANYL CITRATE', 62.704, -83.07);
insert into Punishments (name, serverity, trigger_score) values ('Miconazorb AF Powder', 59.703, -31.5);
insert into Punishments (name, serverity, trigger_score) values ('Hydrocodone Bitartrate and Acetaminophen', 45.094, -74.78);
insert into Punishments (name, serverity, trigger_score) values ('Titanium Dioxide', 19.883, -42.68);
insert into Punishments (name, serverity, trigger_score) values ('Octinoxate', 64.801, -33.14);
insert into Punishments (name, serverity, trigger_score) values ('ARIPIPRAZOLE', 98.451, -44.4);
insert into Punishments (name, serverity, trigger_score) values ('amitriptyline hydrochloride', 93.897, -45.11);
insert into Punishments (name, serverity, trigger_score) values ('ZINC ACETATE ANHYDROUS and ZINC GLUCONATE', 2.947, -45.13);
insert into Punishments (name, serverity, trigger_score) values ('Ensulizole', 46.383, -22.55);
insert into Punishments (name, serverity, trigger_score) values ('synthetic conjugated estrogens, A', 41.832, -28.39);
insert into Punishments (name, serverity, trigger_score) values ('Execution', 7, -99.99);
